# Generated by Django 3.1.3 on 2020-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20201128_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='comment_user',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
