# Generated by Django 3.1.2 on 2020-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
