# Generated by Django 3.1.2 on 2020-10-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_left',
            field=models.IntegerField(default=0),
        ),
    ]
