# Generated by Django 3.1.2 on 2020-10-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_budget_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='budget_left',
        ),
    ]
