# Generated by Django 3.1.2 on 2020-10-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201031_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Link_to_image',
            new_name='link_to_image',
        ),
    ]
