# Generated by Django 3.1.2 on 2020-10-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_expense_expense_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_pk',
        ),
        migrations.AddField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
            preserve_default=False,
        ),
    ]
