# Generated by Django 3.2.6 on 2021-08-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
