# Generated by Django 3.2.6 on 2021-08-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210827_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skills'),
        ),
    ]
