# Generated by Django 3.2.6 on 2021-08-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210827_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
