# Generated by Django 3.2.6 on 2021-08-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='experience_level',
            field=models.IntegerField(default=1),
        ),
    ]
