# Generated by Django 3.2.6 on 2021-08-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210827_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='value',
        ),
    ]
