# Generated by Django 3.2.6 on 2021-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_skills_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
