# Generated by Django 3.1.1 on 2020-10-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0006_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')]),
        ),
    ]
