# Generated by Django 3.1.1 on 2020-10-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0007_auto_20201008_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[('Easy', 1), ('Medium', 2), ('Hard', 3)]),
        ),
    ]
