# Generated by Django 3.1.2 on 2020-10-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201019_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Parrot', 'Parrot'), ('animal', 'animal')], default='animal', max_length=6),
        ),
    ]
