# Generated by Django 3.1.2 on 2020-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201023_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.CharField(default='like', max_length=4),
        ),
    ]
