# Generated by Django 3.1.2 on 2020-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(blank=None, default='like', max_length=4),
        ),
    ]
