# Generated by Django 3.1.3 on 2020-11-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201128_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='comment_user',
        ),
    ]
