# Generated by Django 3.1.4 on 2020-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20201129_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('pic', 'pic'), ('mod', 'mod')], default=None, max_length=7),
        ),
    ]
